### ISSUE TITLE
Version mismatches? 

### ISSUE THREAD

**Issue by shaiguitar** [rothgar/docker-hubot#2]
Following README:

```
....
$ docker run --env-file ./ENV -v /etc/localtime:/etc/localtime:ro --name hubotbot hubotbot
/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/resolver.js:165
    let lookup = path.join(...parts.slice(0, i + 1), 'node_modules');
                           ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:14:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

**Comment by rothgar** [comment]
This is really old and I no longer use it. I'd welcome a PR to fix the issue but it probably needs work to stay up to date.

I'm going to archive the project just so it's not assumed the project should work after not being touched for more than a year.
